version: "3"
services:
  db:
    image: mysql
    ports:
      - "9000:3036"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_TCP_PORT: 3036
      MYSQL_DATABASE: BoardApiProject
    restart: unless-stopped
  api:
    build: .
    image: tttapi
    ports:
      - "8082:8080"
    volumes:
      - ./cont_logs:/app/logs
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://db:3036/BoardApiProject?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true",
        "spring.datasource.password": "root"
      }'
    restart: on-failure
    depends_on:
      - db
  ui:
    image: nginx
    ports:
      - "82:80"
    volumes:
      - ./src/main/resources/static:/usr/share/nginx/html
    depends_on:
      - api
    restart: unless-stopped